---
dependency:
  name: galaxy

lint: |
  yamllint .
  ansible-lint .

driver:
  name: docker

platforms:
  - name: single-node-cluster-docker
    image: my-own/docker-centos7-ansible-ssh:latest
    dockerfile: Dockerfile.j2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: false
    override_command: false
    exposed_ports:
      - 9780/tcp
      - 8088/tcp
    published_ports:
      - 0.0.0.0:9780:9780/tcp
      - 0.0.0.0:8088:8088/tcp

provisioner:
  name: ansible

verifier:
  name: ansible

scenario:
  test_sequence:
    - destroy
    - lint
    - dependency
    - create
    - converge
    - verify
    - destroy
